### ISSUE TITLE
Concerns about comparisons

### ISSUE THREAD

**Issue by DachunKai** [zkawfanx/RLP#2]
Excellent work！

Would it be appropriate to consider comparing it with two-stage methods that incorporate low-light enhancement algorithms for nighttime scenes along with deraining?

**Comment by zkawfanx** [comment]
It is reasonable to consider low light enhancement together with nighttime deraining since real night rainy images indeed face noise problems, especially for real images collected from the Internet.

At this moment, our method and training data do not take the noise problem into account yet, but feel free to make comparsions and see what we can get here.

However, I may have some concerns on the experimental setting you are talking about, i.e., what kind of scenes you want to handle. Please note that, in most cases, you need to get the camera towards the light sources and select long enough exposure time and proper ISO to ensure rain streaks are obvious and visible on the captured night rainy image. This may misalign the noise property with common low light enhancement setting, I guess. Hope it can help.
